# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.Car'),
        ),
    ]
