# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-10 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_insuranceaddon_privatedriveraddon_trackdayaddon'),
        ('checkout', '0002_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='addon',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.InsuranceAddon'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='private_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.PrivateDriverAddon'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='track_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.TrackDayAddon'),
        ),
    ]
