# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200714_1635'),
        ('checkout', '0003_auto_20200710_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItemCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_days', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItemInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_days', models.IntegerField()),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.InsuranceAddon')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItemPDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItemTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_days', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.Car'),
        ),
        migrations.AddField(
            model_name='order',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.InsuranceAddon'),
        ),
        migrations.AddField(
            model_name='order',
            name='private_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.PrivateDriverAddon'),
        ),
        migrations.AddField(
            model_name='order',
            name='track_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.TrackDayAddon'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.Car'),
        ),
        migrations.AddField(
            model_name='orderlineitemtrack',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
        migrations.AddField(
            model_name='orderlineitemtrack',
            name='track_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.TrackDayAddon'),
        ),
        migrations.AddField(
            model_name='orderlineitempdriver',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
        migrations.AddField(
            model_name='orderlineitempdriver',
            name='private_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.PrivateDriverAddon'),
        ),
        migrations.AddField(
            model_name='orderlineiteminsurance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
        migrations.AddField(
            model_name='orderlineitemcar',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
    ]
