# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200716_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitemcar',
            name='car',
        ),
        migrations.RemoveField(
            model_name='orderlineitemcar',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineiteminsurance',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='orderlineiteminsurance',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineitempdriver',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineitempdriver',
            name='private_driver',
        ),
        migrations.RemoveField(
            model_name='orderlineitemtrack',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineitemtrack',
            name='track_day',
        ),
        migrations.DeleteModel(
            name='OrderLineItemCar',
        ),
        migrations.DeleteModel(
            name='OrderLineItemInsurance',
        ),
        migrations.DeleteModel(
            name='OrderLineItemPDriver',
        ),
        migrations.DeleteModel(
            name='OrderLineItemTrack',
        ),
    ]
