# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-10 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('Track Day', 'Track Day'), ('Track Coach', 'Track Coach'), ('Basic Insurance', 'Basic Insurance'), ('Standard Insurance', 'Standard Insurance'), ('Full Insurance', 'Full Insurance'), ('Private Driver', 'Private Driver')], max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(max_length=500)),
                ('image1', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_class', models.CharField(choices=[('Custom Classic', 'Custom Classic'), ('Luxury', 'Luxury'), ('Supersport', 'Supersport')], max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.CharField(default='', max_length=30)),
                ('model', models.CharField(default='', max_length=30)),
                ('year', models.DecimalField(choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], decimal_places=0, max_digits=4)),
                ('track_day', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=40)),
                ('engine_type', models.CharField(choices=[('Inline 3', 'Inline 3'), ('Inline 4', 'Inline 4'), ('Inline 6', 'Inline 6'), ('Boxer 4', 'Boxer 4'), ('Boxer 6', 'Boxer 6'), ('V6', 'V6'), ('V8', 'V8'), ('V10', 'V10'), ('V12', 'V12'), ('W10', 'W10'), ('W12', 'W12'), ('Other', 'Other')], max_length=40)),
                ('displacement', models.DecimalField(decimal_places=1, max_digits=4)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Full Electric', 'Full Electric'), ('Hybrid', 'Hybrid'), ('Petrol', 'Petrol')], max_length=50)),
                ('passengers', models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], decimal_places=0, max_digits=10)),
                ('doors', models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], decimal_places=0, max_digits=10)),
                ('accessories', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Custom', 'Custom')], max_length=20)),
                ('city', models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway')], max_length=30)),
                ('county', models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway')], default='', max_length=30)),
                ('country', models.CharField(choices=[('Ireland', 'Ireland')], max_length=10)),
                ('image1', models.ImageField(upload_to='media/images')),
                ('image2', models.ImageField(upload_to='media/images')),
                ('image3', models.ImageField(upload_to='media/images')),
                ('image4', models.ImageField(upload_to='media/images')),
                ('image5', models.ImageField(upload_to='media/images')),
                ('guidelines', models.TextField(max_length=500)),
                ('car_owner', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
