# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.CharField(default='', max_length=30)),
                ('model', models.CharField(default='', max_length=30)),
                ('year', models.CharField(default='', max_length=4)),
                ('engine', models.CharField(default='', max_length=10)),
                ('accessories', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=10)),
                ('county', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=10)),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('image3', models.ImageField(upload_to='images')),
                ('image4', models.ImageField(upload_to='images')),
                ('image5', models.ImageField(upload_to='images')),
                ('guidelines', models.TextField()),
            ],
        ),
    ]
