# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-08 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_day',
            new_name='price',
        ),
    ]
