# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-10 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200710_2135'),
        ('cars', '0002_insuranceaddon_privatedriveraddon_trackdayaddon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addon',
        ),
    ]
