# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_auto_20200618_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
