# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200618_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
