# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user_id',
        ),
    ]
