# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200703_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='accessories',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='county',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway')], max_length=30),
        ),
    ]
