# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200616_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'AT'), ('Manual', 'MT')], max_length=10),
        ),
    ]
