# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
