# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200616_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('Custom Classic', 'CC'), ('Luxury', 'LX'), ('Supersport', 'SS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Dublin', 'DUB'), ('Cork', 'COR'), ('Galway', 'GAL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('Ireland', 'IRE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='county',
            field=models.CharField(choices=[('Dublin', 'CTDUB'), ('Cork', 'CTCOR'), ('Galway', 'CTGAL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Diesel', 'D'), ('Full Electric', 'E'), ('Hybrid', 'H'), ('Petrol', 'P')], max_length=40),
        ),
    ]
